name: Test
on: workflow_dispatch

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hahhah"
    - name: Trigger pacakges update
      run: |
        gitdate=$(curl -H "Authorization: token ${{ secrets.TOKEN_KIDDIN9 }}" -s "https://api.github.com/repos/kiddin9/openwrt-packages/actions/runs" | jq -r '.workflow_runs[0].created_at')
        gitdate=$(date -d "$gitdate" +%s)
        echo gitdate
  
